# Generated by Django 3.1.6 on 2021-02-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='버전')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kr', models.CharField(max_length=15, verbose_name='이름')),
                ('name_en', models.CharField(max_length=50, verbose_name='Name')),
                ('blurb', models.TextField(blank=True, verbose_name='이야기')),
                ('image_full', models.CharField(max_length=50, verbose_name='아이콘 이미지')),
                ('image_group', models.CharField(max_length=50, verbose_name='이미지 그룹')),
                ('image_sprite', models.CharField(max_length=50, verbose_name='스프라이트 이미지')),
                ('image_sprite_x', models.SmallIntegerField(verbose_name='스프라이트 x')),
                ('image_sprite_y', models.SmallIntegerField(verbose_name='스프라이트 y')),
                ('image_sprite_w', models.SmallIntegerField(verbose_name='스프라이트 w')),
                ('image_sprite_h', models.SmallIntegerField(verbose_name='스프라이트 h')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lol.version', verbose_name='버전')),
            ],
        ),
    ]
