# Generated by Django 3.1.6 on 2021-02-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_champion_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champion',
            options={'verbose_name': '챔피언', 'verbose_name_plural': '챔피언'},
        ),
        migrations.AlterModelTable(
            name='champion',
            table='lol_champion',
        ),
    ]
